#  
# from random import randint

# def win():
#     print ('You win!')

# def lose():
#     print ('You lose!')

# while True:
#     player_choice = input('What do you pick? (rock, paper, scissors)')
#     player_choice.strip()
#     random_moves = randint(0, 2)
#     moves = ['rock', 'paper', 'scissors']
#     computer_choice = [random_moves]
#     print(computer_choice)

#     if player_choice == computer_choice:
#         print('choice your option')
#     elif player_choice  == 'rock' or computer_choice == 'scissors':
#         win()
#     elif player_choice  == 'paper' or computer_choice == 'scissors':
#         lose()
#     elif player_choice == 'scissors' or computer_choice == 'paper':
#         win()
#     elif player_choice == 'scissors' or computer_choice == 'rock':
#         lose()
#     elif player_choice == 'paper' or computer_choice == 'rock':
#         win()
#     elif player_choice == 'rock' and computer_choice == 'paper':
#         lose()
#     again = input('Do you want to play again? (y or n)').strip()
#     if again == 'n':
#         break





# marks = [
#     [78, 76, 94, 86, 88],
#     [91, 71, 98, 65, 76],
#     [95, 45, 78, 52, 49]
# ] 

# i=0
# sum=0
# while i<len(marks):
#     j=0
#     a=0
#     while j<len(marks[i]):
#         a=a+marks[i][j]
#         j=j+1
#     sum=sum+a
#     i=i+1
# print(sum)
# avg=sum/15
# print("avg","=",avg)




 
number = 30
n = [10, 11, 12, 13, 14, 17, 18, 19] 

i=0
b=[]
while i<len(n):
    a=0
    while a<len(n):
        if n[i]+n[j]==number:











 
marks = [
    [78, 76, 94, 86, 88],
    [91, 71, 98, 65, 76],
    [95, 45, 78, 52, 49]
]

i=0
avg=0
count=0
while i<len(marks):
    sum=0
    a=0
    j=0
    while i<len(marks):








